### ISSUE TITLE
Why are we not on the main Node School

### ISSUE THREAD

**Issue by inidaname** [NodeJSAfrica/nodeschool-organizers#1]
Just my curiosity but why is this in a different repo, it good to see something new but guide and community maintenance is always one primary issue when you approach Open Source, believe me I am always down for whatever will move the NodeJs community forward and contributing to Open Source is always my drive.

Looking forward to working with you

**Comment by codeekage** [comment]
That's primarily for making plans within us as Africans... before taking it
to the World.

**Comment by flickz** [comment]
Oh cool
