### ISSUE TITLE
The Structure

### ISSUE THREAD

**Issue by inidaname** [NodeJSAfrica/nodeschool-organizers#2]
Hello @codeekage 

Can we discuss a more concrate direction 

- First I notice I joined but probably removed, I will blame my change of authentication settings
- Please send the IV again

My request is we can start this by spreading the awareness through the proper channels to get more people on board.
From there we can raise series of issues on the Node.Js core team collaboration

Waiting for your response

**Comment by flickz** [comment]
Are we under nodeschool?

**Comment by inidaname** [comment]
Hello @flickz 
We are not under Node School more to say we are more of community organization for African Node.js Developers _This is still need more_

**Comment by flickz** [comment]
@inidaname Think we really need to have a meeting and discuss this.

**Comment by inidaname** [comment]
I proposed The Port Harcourt event shouldn't just be the NodeSchool it should also mark the pioneer meeting for the future of this.

Let me cc all in this org for notification, a +1 one can confirm your agreement to the proposal
@flickz @codehakase @achowba @codeekage @devamaz
