### ISSUE TITLE
Requesting to add new members

### ISSUE THREAD

**Issue by inidaname** [NodeJSAfrica/nodeschool-organizers#4]
Hello
Please send invitation to the list below
@devamaz
@blackdevelopa

Can I suggest you send invitation to anyone requesting to open NodeSchool on the nodeschool.io
Thank You

**Comment by codeekage** [comment]
Awesome!

**Comment by inidaname** [comment]
Hello
@codeekage I reopened issue because @blackdevelopa said he couldn't accept the Invitation link sent to him I don't know how but may be you send him another link

**Comment by blackdevelopa** [comment]
Hello @codeekage kindly resend an invitation link please. Thank you.
@inidaname Thank you reopening this.
